#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# do not allow system rc files to clobber the configuration
setopt no_global_rcs

# Report CPU usage for commands running longer than 10 seconds
REPORTTIME=10

# groovy support
export GROOVY_HOME=/usr/local/opt/groovy/libexec

# octave, actually gnuplot
export GNUTERM="qt"

# Oracle support
if [ -d $HOME/Tools/oracle ]; then
  export DYLD_LIBRARY_PATH=$HOME/Tools/oracle
  export ORACLE_HOME=$DYLD_LIBRARY_PATH
  export OCI_HOME=$DYLD_LIBRARY_PATH
  export OCI_LIB_DIR=$DYLD_LIBRARY_PATH
  export OCI_INC_DIR=$DYLD_LIBRARY_PATH/sdk/include
fi
if [ "$(uname)" = "Linux" ]; then
  export LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH
fi


# Java support
if [ -x /usr/libexec/java_home ]
then
  export JAVA_HOME=`/usr/libexec/java_home`
fi

# private environment variables not checked in
if [ -f ~/.private.zsh ]
then
  source ~/.private.zsh
fi


### gtags support
export GTAGSLABEL=pygments

# OpenSSL support on OSX
if [ "$(uname)" = "Darwin" ]; then
  export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
fi


# Sonarqube support
if [ -d "/usr/local/Cellar/sonar-runner/2.7/libexec" ]; then
  SONAR_RUNNER_HOME=/usr/local/Cellar/sonar-runner/2.7/libexec
  export SONAR_RUNNER_HOME
fi

if [[ "$(uname -v)" == *"Microsoft"* ]]; then
  export DOCKER_HOST=tcp://localhost:2375
fi

# github extension for git
if [ -x "`where hub`" ]; then
   eval $(hub alias -s)
fi


