#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# add local path
PATH=$PATH:~/bin


# golang support
export GOPATH=~/playpen/go
export PATH=$PATH:$GOPATH/bin:/usr/local/opt/go/libexec/bin

# perl5 build
PERL_MB_OPT="--install_base \"/Users/pti/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/pti/perl5"; export PERL_MM_OPT;


# octave
export GNUTERM="qt"
export DYLD_LIBRARY_PATH=/Users/pti/Tools/oracle
export ORACLE_HOME=$DYLD_LIBRARY_PATH
export OCI_LIB_DIR=$DYLD_LIBRARY_PATH
export OCI_INC_DIR=$DYLD_LIBRARY_PATH/sdk/include

# java support
# for Java <8 : max perm size tends to fill up, increase it
# export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128M"
# for Java8 and later this is no longer needed
export MAVEN_OPTS="-Xmx512m"

if [ -x /usr/libexec/java_home ]
then
    export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
fi

### GPG-agent
GPG_TTY=$(tty)
export GPG_TTY
if [ -f "${HOME}/.gpg-agent-info" ]; then
    . "${HOME}/.gpg-agent-info"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
export KAGGLE_BOSCH_DATA_ROOT=~/Dropbox/kaggle

### Rust support

# add cargo bin directory to path
export PATH=$PATH:~/.cargo/bin

# to enable racer RUST code expansion
export RUST_SRC_PATH=~/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src

# added by Anaconda3 installer
export PATH="$PATH:/Users/pti/anaconda3/bin"

if [ -f ~/.private.zsh ]
then
    source ~/.private.zsh
fi

### Haskell support
export PATH=$PATH:~/Library/Haskell/bin
