#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...
if [[ "$OSTYPE" =~ "darwin.*" ]]
then
    alias rgrep=grep -r
    alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'

    # show/hide hidden files in OSX file browsers
    alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
fi

export EDITOR=~/bin/ec
export VISUAL=$EDITOR

# Report CPU usage for commands running longer than 10 seconds
REPORTTIME=10

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# map gpg2 on regular gpg
alias gpg=gpg2

#
# GPG agent
#
# start gpg-agent and generate file with socket connection info
#
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh


# Haskell/Stack aliases
alias runhaskell='stack runhaskell'
alias ghc='stack exec ghc --'
alias ghci='stack exec ghci --'

# add exercism completion to zsh
if [ -f ~/bin/shell/exercism_completion.zsh ]; then
  echo added exercism completion
fi
