# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# -*- encoding=utf-8 -*-
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...
#
# PTI: this is the place to add aliases, functions and other
# useful things for interactive work on the command line.
#

if [[ "$OSTYPE" =~ "darwin.*" ]]
then
  alias rgrep=grep -r
  alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'

  # show/hide hidden files in OSX file browsers
  alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
  alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
fi


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# map gpg2 on regular gpg
alias gpg=gpg2


# change cursor shape
echo -ne "\e[5 q" # start in insert mode
zle-keymap-select () {
  if [[ $TERM =~ .*-256color ]]; then
    if [ $KEYMAP = vicmd ]; then
      # the command mode for vi
      echo -ne "\e[2 q"
    else
      # the insert mode for vi
      echo -ne "\e[5 q"
    fi
  fi
  zle reset-prompt
  zle -R
}

# start emacs daemon if not yet running
if (ps ax | grep -e '[[:digit:]] emacs --daemon' >/dev/null)
then
else
  emacs --daemon
fi
export ALTERNATE_EDITOR=""

# support for jfrog tool
if [ -e "$HOME/.jfrog/jfrog_zsh_completion" ]; then
   autoload -Uz compinit
   compinit
   source /home/pti/.jfrog/jfrog_zsh_completion
fi

# opam configuration
test -r /home/pti/.opam/opam-init/init.zsh && . /home/pti/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
